### ISSUE TITLE
Wordpress plugin

### ISSUE THREAD

**Issue by Mte90** [sniphpets/sniphpets#1]
If I want to do a WordPress plugin for sniphpets, what is the workflow?

**Comment by voronkovich** [comment]
@Mte90, There is no workfolw :). All snippets is built on the top of the great [Ultisnips](https://github.com/SirVer/ultisnips) plugin. This repository is just a collection of useful functions for the Vim like `namespace`, `basename`, `ucfirst`, `lcfirst` and etc. The good example of snippets you can find here: https://github.com/sniphpets/sniphpets-phpunit.

If you want I could add you to the sniphpets organization so you will be able to create a repository here.

**Comment by Mte90** [comment]
Thanks, I was thinking that was automatically generated.
Later I found https://github.com/sudar/vim-wordpress-snippets, maybe is better to integrate this one then make a new one
